'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Loader2, FileText } from 'lucide-react';
import { reportApi, ReportSummary } from '@/lib/api';
import { ReportCard } from '@/components/reports/ReportCard';
import { ReportFilter } from '@/components/reports/ReportFilter';
import { useToast } from '@/components/ui/toast';
import { RequireAuth } from '@/components/layout/RequireAuth';

export default function ReportsPage() {
  const { toast } = useToast();
  const [reports, setReports] = useState<ReportSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await reportApi.list({ limit: 200 });
      setReports(res.data);
    } catch {
      toast('error', 'Failed to load reports');
    } finally {
      setLoading(false);
    }
  }, [toast]);

  useEffect(() => {
    void load();
  }, [load]);

  const filtered = useMemo(() => {
    const needle = search.trim().toLowerCase();
    return reports.filter((report) => {
      if (statusFilter !== 'all' && report.compliance_status !== statusFilter) return false;
      if (!needle) return true;
      return (
        report.title.toLowerCase().includes(needle) ||
        (report.scan_ref ?? '').toLowerCase().includes(needle) ||
        report.report_id.toLowerCase().includes(needle)
      );
    });
  }, [reports, search, statusFilter]);

  const handleDownload = useCallback(
    async (reportId: string) => {
      try {
        const res = await reportApi.download(reportId);
        const url = URL.createObjectURL(res.data as Blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `MetroCheck_Report_${reportId.slice(0, 8)}.pdf`;
        a.click();
        URL.revokeObjectURL(url);
        return true;
      } catch {
        toast('error', 'Download failed', 'The report file could not be downloaded.');
        return false;
      }
    },
    [toast]
  );

  const handleDelete = useCallback(
    async (reportId: string) => {
      if (!window.confirm('Delete this report permanently?')) return;
      try {
        await reportApi.delete(reportId);
        await load();
        toast('success', 'Report deleted');
      } catch {
        toast('error', 'Delete failed', 'Could not delete this report.');
      }
    },
    [load, toast]
  );

  return (
    <RequireAuth>
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Compliance Reports</h1>
          <p className="mt-1 text-sm text-slate-500">
            Official PDF and JSON inspection reports generated by MetroCheck
          </p>
        </div>

        <ReportFilter onSearch={setSearch} onStatusFilter={setStatusFilter} />

        {loading ? (
          <div className="flex h-48 items-center justify-center gap-3 text-slate-500">
            <Loader2 className="h-6 w-6 animate-spin" />
            Loading reports...
          </div>
        ) : filtered.length === 0 ? (
          <div className="rounded-xl border border-dashed border-slate-300 bg-white/50 p-12 text-center">
            <FileText className="mx-auto h-10 w-10 text-slate-300" />
            <p className="mt-3 font-medium text-slate-600">No reports found</p>
            <p className="mt-1 text-sm text-slate-400">
              {reports.length === 0
                ? 'Complete a compliance scan to generate your first report.'
                : 'No reports match your current filters.'}
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
            {filtered.map((report) => (
              <ReportCard
                key={report.report_id}
                report={report}
                onDownload={handleDownload}
                onDelete={handleDelete}
              />
            ))}
          </div>
        )}
      </div>
    </RequireAuth>
  );
}